import { AVSMockData } from "./types";

export const mockData: AVSMockData[] = [
  {
    name: "EigenDA",
    slashing: "Low",
    rewards: "High",
    openSource: true,
    decentralized: true,
    protocolInteroperability: ["18+ Different DA consumers "],
    riskScore: {
      slashing: 0,
      rewards: 100,
      openSource: 100,
      decentralized: 50,
      interoperability: 100,
    },
  },
  {
    name: "eoracle",
    slashing: "Low",
    rewards: "Low",
    openSource: false,
    decentralized: false,
    protocolInteroperability: ["Any EVM"],
    riskScore: {
      slashing: 80,
      rewards: 0,
      openSource: 0,
      decentralized: 20,
      interoperability: 80,
    },
  },
  {
    name: "Witness Chain",
    slashing: "Low",
    rewards: "Low",
    openSource: true,
    decentralized: false,
    protocolInteroperability: ["Ethereum"],
    riskScore: {
      slashing: 0,
      rewards: 0,
      openSource: 100,
      decentralized: 0,
      interoperability: 0,
    },
  },
  {
    name: "AltLayer MACH",
    slashing: "Low",
    rewards: "Low",
    openSource: false,
    decentralized: false,
    protocolInteroperability: ["Multiple rollup types supported"],
    riskScore: {
      slashing: 0,
      rewards: 0,
      openSource: 0,
      decentralized: 0,
      interoperability: 80,
    },
  },
  {
    name: "Hyperlane AVS",
    slashing: "Low",
    rewards: "Low",
    openSource: false,
    decentralized: false,
    protocolInteroperability: [
      "deployed on more than 35 EVM, Cosmos, and Sealevel chains",
    ],
    riskScore: {
      slashing: 0,
      rewards: 0,
      openSource: 0,
      decentralized: 0,
      interoperability: 80,
    },
  },
];
